version: '3.8'
services:
  db:
    ports:
      - "5434:5432"
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit_user
      - POSTGRES_PASSWORD=qwerty
  server:
    build: ./server
    ports:
      - "8081:8081"
      - "8084:8084"
    depends_on:
      - db
    environment:
      - HOST=db
      - PORT=5432
      - DB_NAME=shareit
      - POSTGRES_USER=shareit_user
      - POSTGRES_PASSWORD=qwerty
      - "TZ=Europe/Moscow"
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
      - "8083:8083"
    environment:
      - SERVER_URL=http://server:8081
      - "TZ=Europe/Moscow"